// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType & DisallowNamespaces
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation & DisallowNamespaces

export type Translations = RootTranslation &
{
	auth_login: NamespaceAuthLoginTranslation,
	home: NamespaceHomeTranslation
}

type RootTranslation = {
	/**
	 * Y​o​u​r​ ​t​o​t​a​l​ ​a​m​o​u​n​t​ ​i​s​ ​{​a​m​o​u​n​t​|​U​S​D​}​.
	 * @param {number} amount
	 */
	TotalAmountUSD: RequiredParams<'amount|USD'>
	/**
	 * Y​o​u​ ​t​o​t​a​l​ ​a​m​o​u​n​t​ ​i​s​ ​{​a​m​o​u​n​t​|​c​u​r​r​e​n​c​y​|​M​M​K​}
	 * @param {number} amount
	 */
	TotalAmountMMK: RequiredParams<'amount|currency|MMK'>
}

export type NamespaceAuthLoginTranslation = {
	Email: {
		/**
		 * E​m​a​i​l
		 */
		Label: string
	}
	Password: {
		/**
		 * P​a​s​s​w​o​r​d
		 */
		Label: string
	}
	LoginForm: {
		Validation: {
			Email: {
				/**
				 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​.
				 */
				Required: string
				/**
				 * I​n​c​o​r​r​e​c​t​ ​e​m​a​i​l​ ​f​o​r​m​a​t​.
				 */
				Format: string
			}
			Password: {
				/**
				 * P​l​e​a​s​e​ ​e​n​t​e​r​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​.
				 */
				Required: string
				/**
				 * P​a​s​s​w​o​r​d​ ​m​u​s​t​ ​b​e​ ​8​ ​t​o​ ​3​2​ ​c​h​a​r​a​c​t​e​r​s​.
				 */
				Length: string
			}
		}
	}
}

export type NamespaceHomeTranslation = {
	/**
	 * H​e​l​l​o​ ​f​r​o​m​ ​R​e​a​c​t​ ​+​ ​T​y​p​e​s​c​r​i​p​t​ ​+​ ​V​i​t​e
	 */
	Heading: string
}

export type Namespaces =
	| 'auth_login'
	| 'home'

type DisallowNamespaces = {
	/**
	 * reserved for 'auth_login'-namespace\
	 * you need to use the `./auth_login/index.ts` file instead
	 */
	auth_login?: "[typesafe-i18n] reserved for 'auth_login'-namespace. You need to use the `./auth_login/index.ts` file instead."

	/**
	 * reserved for 'home'-namespace\
	 * you need to use the `./home/index.ts` file instead
	 */
	home?: "[typesafe-i18n] reserved for 'home'-namespace. You need to use the `./home/index.ts` file instead."
}

export type TranslationFunctions = {
	/**
	 * Your total amount is {amount|USD}.
	 */
	TotalAmountUSD: (arg: { amount: number }) => LocalizedString
	/**
	 * You total amount is {amount|currency|MMK}
	 */
	TotalAmountMMK: (arg: { amount: number }) => LocalizedString
	auth_login: {
		Email: {
			/**
			 * Email
			 */
			Label: () => LocalizedString
		}
		Password: {
			/**
			 * Password
			 */
			Label: () => LocalizedString
		}
		LoginForm: {
			Validation: {
				Email: {
					/**
					 * Please enter your email.
					 */
					Required: () => LocalizedString
					/**
					 * Incorrect email format.
					 */
					Format: () => LocalizedString
				}
				Password: {
					/**
					 * Please enter your password.
					 */
					Required: () => LocalizedString
					/**
					 * Password must be 8 to 32 characters.
					 */
					Length: () => LocalizedString
				}
			}
		}
	}
	home: {
		/**
		 * Hello from React + Typescript + Vite
		 */
		Heading: () => LocalizedString
	}
}

export type Formatters = {
	currency: (value: number) => unknown
	MMK: (value: number) => unknown
	USD: (value: number) => unknown
}
